server:
  port: 80
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : product
          uri : lb://product
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id : review
          uri : lb://review
          predicates:
            - Path=/review/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id : order
          uri : lb://order
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id : user
          uri : lb://user
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://3.143.74.33:8761/eureka


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.ipc.netty: DEBUG
