server:
  port: 0

spring:
  application:
    name: product
  cloud:
    bootstrap:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      show_sql : true
  datasource:
    url: jdbc:mariadb://localhost:3308
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

