server:
  port: 0
  address: 0.0.0.0
  servlet:
    context-path: /product

spring:
  application:
    name: product
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config
      name: product
      profile: default

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.143.74.33:8761/eureka