server:
  port: 0

spring:
  application:
    name: product
  cloud:
    bootstrap:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      show_sql : true
  datasource:
    url: jdbc:mariadb://localhost:3308/test?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

