server:
  port: 0
  forward-headers-strategy: framework

spring:
  application:
    name: cart
  cloud:
    bootstrap:
      enabled: true

springdoc:
  swagger-ui:
    path: /cart-swagger
    operations-sorter: method

